### ISSUE TITLE
🎫 Valide a Event Ticket through QR Code for employee / POS Seat

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1067]
On event entry, people will scan the event QR code with their phone.
For now let's go with android device.
To avoid to have sessionless browser (like visualization browser, like when you open a link from Messenger on Android), and instead on going GAFAM with Google Lens, we can use this opensource solution :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/0461e650-5264-4a20-bbf3-ec80fd160330)
https://markusfisch.de/apps-android.html
https://play.google.com/store/apps/details?id=de.markusfisch.android.binaryeye
https://github.com/markusfisch/BinaryEye
https://github.com/markusfisch/BinaryEye/releases (for APK, if people are de-googleized)
I've tried it on my phone :
- QR code dense like this is easily readable
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/23b906c6-c4f9-4f8f-a4c3-e5a1c8a4bccb)
- Link is opened in the main browser, so if the employee is logged on employee or POS Seat, he/she'll have employee features contrary to this preview default android browser (because session won't be up on this)
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/e03d4086-a9ae-417f-bde2-d02049e8350b)
So, when logged as employee, add a "Mark ticket as used" button.
Once done, replace with a "Already used" disable button.
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/68d2a285-a963-4179-901a-d572ab28b4d0)
For super-admin, in case of issue, allow to unburn an even ticket :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/86d215a7-2632-4363-aca7-58386d916986)
And if something happens with the QR code reading, people can send customers to a POS Seat, where the people will be able to check the order in transaction/order, if the customer show the order, the burn can be done manually.

**Comment by coyotte508** [comment]
Reopened - the role was created but the burn/unburn of the ticket remains
