### ISSUE TITLE
📡 Allow a POS seat to overwrite its IP country on POS Session with a manually selected country

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1186]
# Context
With a VAT behavior where VAT rate = VAT rate from customer country, we had to make sales on Belgium, with specific articles and belgian VAT.
Onsite, we had no wiFi, and through 4G, we had a french IP (it was a french SIM card). We tried to go through a belgian VPN, but it was very flaky and not a viable option.
So, in order to sell during this belgian week-end, we had to change the VAT behavior and put the main website in maintenance as beBOP didn't locate us in Belgium with our only connexion options.

# Behavior
On /pos, add an option "Overwrite IP country for this POS Session with selected country" + display the current country deduced from IP.
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/2b471f51-c74e-4948-8bd2-c54845da23c7)
Once checked a country selected, display a warning :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/a5d6d473-82b6-4161-a4f7-26c6cd360686)
English default text :
"Are you sure ? This can have impact on law compliance with your sales and invoices. Do it only if you're sure about it and if the owner requested it."
French default text :
"Êtes vous sur ? Ceci peut avoir un impact sur la légalité de vos ventes et leur facturation. Ne le faites que si vous êtes sur de vous, et que si le propriétaire l'a demandé."

**Then**, for the rest of the POS session, consider the POS seat to be located in the chosen country instead of the one from the IP (I think it's easier to say that done, despite being just one line of description).

The IP country overwrite should be as displayed previously :
"This update will be active only during the current session. If you change browser, computer or have to login again, it'd be resetted."

**Comment by coyotte508** [comment]
Yes it's possible, we can have it for the session or associated to the user (eg in personal info)

**Comment by Tirodem** [comment]
If both are possible, I feel it's better in session (the documentation will
recommand 1 day of session expiration for POS Seat, that'll avoir POS
seater to forget to change the account country once back in it).
