### ISSUE TITLE
☢️ Free cart cannot be ordered (anymore ?)

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1193]
Related to https://github.com/B2Bitcoin/beBOP/issues/1179 / https://github.com/B2Bitcoin/beBOP/pull/1182

Here's the current behavior on a cart at 0 with free product :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/aac8e0e5-ff95-47d8-931d-70481b36263e)
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/9573f117-f9d6-4efd-b64f-c4dfd36db2cf)

I'm nearly sure it worked in the past, but that's not the point, so as #1120 is progressing, here's how I see the thing :
- create a new payment method "Nothing to pay (free cart)"
- when cart amount to pay = 0, only display this payment mean
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/8bb7a592-482b-42a2-859f-ad8aa3c37c0b)
- when processing the checkout, create the payment directly at "paid" status

**Comment by coyotte508** [comment]
related to 100% discount cc @ithiame

**Comment by Tirodem** [comment]
Sure, but to be clearer on the "why", I created the issue because selling
cart with free product is for now more important that 100% discount on POS,
that is a nice to have (but allowed to find the issue).
