### ISSUE TITLE
♻️ Change be-BOP logo in Footer

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1228]
Change logo in footer when displaying "powered by be-BOP" :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/f45f23b2-4fd2-41df-8655-bebd51112e3c)

New logo :
![Logo Final Bebop](https://github.com/B2Bitcoin/beBOP/assets/50206014/3a593a0a-1f4c-433f-aa97-92b16a8b08fe)

**Comment by coyotte508** [comment]
We currently have two svgs, one dark and one light. 

Do you have the SVG? Even if you only have the SVG for the light version we can easily make the dark one by replacing the dark blue with white

**Comment by coyotte508** [comment]
if we have both svg it's great  but it's also easy to change the color
