### ISSUE TITLE
🦋 Add an option on POS account checkout : "

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1354]
Following production use case on pilot, we need a new optional option.

1/ in admin/config :
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/f2fe368f-b007-42e6-a215-50ff1d8e66be)

2/ in /checkout
![image](https://github.com/B2Bitcoin/beBOP/assets/50206014/d39f40ff-a5bb-4441-b7b0-0f5b0b4543b7)
when enabled :
- don't display delivery address on receipt
- don't display "billing address" on billing address on receipt
- pre-check POS option "free delivery fees as a POS sale"
- synchronise this checkbox with "free delivery fees as a POS sale" checkbox (if manuallly unchecked, uncheck to, if manuallly rechecked, recheck too)

**Comment by coyotte508** [comment]
Change "full-paid" to "fully-paid" and "shop" to "on-location" in my opinion

And add `onLocation` flag in DB cc @ithiame
