### ISSUE TITLE
👨‍🔬 Add an age limitation on website first access

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1465]
For various law compliance reasons, we need to allow a be-BOP owner to display a mandatory age filter on his / her website, while :
- saying while
- refering to the law compliance reason (url)

Usually, age and age consent is another cookie, but I don't want to add more, for be-BOP native philosophy.

So I'll made proposition but it's open to suggestions.

# 1st thing : admin setting
![image](https://github.com/user-attachments/assets/206d15cd-b442-4a3b-b9c5-287d79c701d2)
![image](https://github.com/user-attachments/assets/4db8550b-e55b-41df-8aad-77900dbf1cff)

# 2nd thing : /home page substitution
While age is not confirmed, whatever link is clicked on the website (even social network), display this page :
![image](https://github.com/user-attachments/assets/596db06d-1cf3-4e99-b24f-37ac95434ca8)
I did the test with `agewalll`, that can be a specific CMS page.
Either we sent every link to this page as long it's not accepted, or we disable every link.
This is, once the age is valitaded, if the user landed from a link to /tartiflette page, after validating the form, the user must land on /tartiflette page (or be locked on this form page forever).

# 3rd thing : cookie management
I'd like to not add another cookie.
@coyotte508 is it possible to overload the bootik-session cookie with this consent or do we need another cookie, like for lang ?

# 4th : confirmation on product addition
Admin :
![image](https://github.com/user-attachments/assets/f5e8a4ec-0446-4341-9ad5-288a6e2929bf)
Product page :
![image](https://github.com/user-attachments/assets/b06550f7-412a-41a4-90ec-fe416e9ea9fb)
Test from # 1 will be displayed again.
Message can be related, or not, depending of https://github.com/B2Bitcoin/beBOP/issues/1187 implementation.

**Comment by coyotte508** [comment]
IMO a separate cookie is the easiest way

**Comment by coyotte508** [comment]
We can add this screen directly in `+layout.svelte` (no redirect)

**Comment by Tirodem** [comment]
@coyotte508 if we introduce a third cookie, don't you think it's time to develop the RGPD alerting ?

**Comment by coyotte508** [comment]
no need it's only needed for tracking/analytics cookie.

Theses cookies are "essential" cookies
