### ISSUE TITLE
🦋 Add price delta on product variation

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1472]
Following https://github.com/B2Bitcoin/beBOP/issues/1466
Add a new input to fill a price delta on variation :
![image](https://github.com/user-attachments/assets/37debfdd-b8c8-4c66-badc-ad775b3e209d)
Currency applied is the same than here :
![image](https://github.com/user-attachments/assets/0dff2c98-786d-4598-8683-87786d8114d5)

On product page, price will be adapted depending of the variations, and will be product price + variation1 price + variation2 price + ... + variationN price.

Variation price delta, as shown in screenshot, can be either positive or negative.
Variation price delta are tax excluded.

**Comment by coyotte508** [comment]
why not
