### ISSUE TITLE
🐛 Product variation improvement 2

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1489]
1/ When creating a variation with value but no name :
![image](https://github.com/user-attachments/assets/1c4cfa7c-d0d3-4e55-8636-03faccd3e1f3)
Save goes on error :
![image](https://github.com/user-attachments/assets/32b35e29-c484-410b-a71b-b01c22e469bf)
On product form, we need to block save and raise front alert if with have a variation with value but empty name.

2/ When creating a variation with numeric name and numeric value :
![image](https://github.com/user-attachments/assets/a9999583-4c07-4327-81ab-c12fb1ca3114)
Here's the result :
![image](https://github.com/user-attachments/assets/02376370-8fbb-4864-8bf5-b65b9e9187f9)
(Having Text/Numeric works, having Numeric/Text works)
It's an exotic case but we need to make it work, it should be processed as a text chain.

**Comment by coyotte508** [comment]
can add a dynamic `required={...}` on the inputs
