### ISSUE TITLE
🐛 Don't lowercase variation value

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1514]
Following https://github.com/B2Bitcoin/beBOP/pull/1491
If values are :
![image](https://github.com/user-attachments/assets/baf0e09b-ccf7-421d-9d1c-bdd043793c15)
Display after add to cart is :
![image](https://github.com/user-attachments/assets/ef94a95b-0063-453b-a33d-8d54c8613153)
It should not be, especially for wear / clothes (XL, S, etc, owners want to sell "L" and not "l").
Please remove the lowercase and put the variation value as it is filled.

**Comment by coyotte508** [comment]
We should use `variationLabels` @ithiame for display (and keep `value` lowercase)
