### ISSUE TITLE
🦋 Change npub session CTA behavior

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1523]
Following https://github.com/B2Bitcoin/beBOP/issues/1483

when /login through npub :
- on desktop
![image](https://github.com/user-attachments/assets/dac961e4-17bc-467c-8702-4639b68293cd)
- on mobile
![image](https://github.com/user-attachments/assets/34eca6bc-5d5a-4884-ac71-953b98173867)

I think we can just display first 5, "(....)" and last 5 digits, for example :
`npub1(...)g4txd`

If we want to to overkill we can make a request through the nostr relay on metadatas to get the content display name on Nostr :
![image](https://github.com/user-attachments/assets/2e25b148-a45d-4394-9302-4e6b2fcd7f3d)
But I think it can lead to performance issues and be overkill (but it can be a nice evolution in the future if performances are better)

**Comment by Tirodem** [comment]
@coyotte508 would metadatas request would be quicker if we just check one information and not the whole thing ?

**Comment by coyotte508** [comment]
metadata request is the same

and we shouldn't rely on the response, maybe we can make the user's browser do the request but it would maybe add some complexity

**Comment by Tirodem** [comment]
Ok, let's keep the partial npub in that case
