### ISSUE TITLE
🦋 Add pagination and filters on /admin/product

### ISSUE THREAD

**Issue by Tirodem** [B2Bitcoin/beBOP#1532]
One of our pilots has performance issues on /admin/product page, due to number of products.
Page can take 10-20 secondes to display.

So implement the same thing as we did with /admin/order :
- [x] for now, display 25 products per page, sorted by updatedAt desc (we'll see with customer feedback)
- [x] introduce the next / previous CTA

It could be done in a second time, but here are the filters that would be interesting for /admin/product :
- [ ] Product name (text input)
- [ ] Product slug (text input)
- [ ] Product type (select menu, "Donation", "Resource", "Subscription")
- [ ] Product attribute (select menu with multiple choices : has physical component, standalone, free, PWYW, etc)
- [ ] Stock (select menu, "No stock management", "With stock", "With no stock")

**Comment by coyotte508** [comment]
How many products are currently displayed & causing prblems?

**Comment by Tirodem** [comment]
Eliott : it's the whole /admin/product page that takes time to load so I'd say "every product".
I tried to display the code from their page and my browser completely froze.
They have 279 products.

**Comment by Tirodem** [comment]
![image](https://github.com/user-attachments/assets/43f2d9a6-1e7b-4016-a020-a4cd90d3d157)

**Comment by Tirodem** [comment]
no prob with 25
