### ISSUE TITLE
Test if bootik works with just invoices.macaroon

### ISSUE THREAD

**Issue by coyotte508** [B2Bitcoin/beBOP#208]
Theorically it's possible for a bootik to work with a remote LND node with just `invoices.macaroon` (may need to configure the LN node url in addition, but that's it)

This would allow trustless LN (and if we support xpub with bitcoin, we'll also have trustless BTC)

**Comment by Tirodem** [comment]
Can we close this one considering implementation of Phoenix Server and BTC on-chain nodeless ?
